version: '3'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    volumes:
      - ./log/zookeeper/data:/var/lib/zookeeper/data
      - ./log/zookeeper/log:/var/lib/zookeeper/log
    networks:
      - kafka_cluster_network
  broker:
    image: confluentinc/cp-kafka:latest
    container_name: broker
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:9092 #,PLAINTEXT_HOST://localhost:29092
      # KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      # KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
    volumes:
      - ./log/broker/data:/var/lib/kafka/data
    networks:
        - kafka_cluster_network
    depends_on:
      - zookeeper

  broker-setup:
    image: confluentinc/cp-kafka:latest
    container_name: broker-setup
    environment:
      KAFKA_BROKER_ID: ignored
      KAFKA_ZOOKEEPER_CONNECT: ignored
    depends_on:
      - broker
    networks:
        - kafka_cluster_network
    command: "bash -c 'echo Waiting for Kafka broker to be ready... && \
              /bin/kafka-topics --create --if-not-exists --topic test-topic \
              --bootstrap-server broker:9092 --partitions 1 --replication-factor 1 && \
              echo List of topics was synchronized - OK'"
              
networks:
  kafka_cluster_network:
    driver: bridge
